/* Allegro datafile object indexes, produced by grabber v3.12 */
/* Datafile: c:\projects\dampbn\res\dampbn.dat */
/* Date: Thu May 11 17:54:36 2023 */
/* Do not hand edit! */

#define RES_ARE_YOU_SURE                 0        /* BMP  */
#define RES_BG_LOWER                     1        /* BMP  */
#define RES_BG_RIGHT                     2        /* BMP  */
#define RES_BUTTONS                      3        /* BMP  */
#define RES_DRAWCURS                     4        /* BMP  */
#define RES_DRAWCURS_SM                  5        /* BMP  */
#define RES_FINISHED                     6        /* BMP  */
#define RES_HELP_EXIT                    7        /* BMP  */
#define RES_HELP_NEXT                    8        /* BMP  */
#define RES_HELP_PREVIOUS                9        /* BMP  */
#define RES_HOLYGOAT                     10       /* BMP  */
#define RES_LG_CROSS                     11       /* BMP  */
#define RES_LG_DIA                       12       /* BMP  */
#define RES_LG_PAL                       13       /* BMP  */
#define RES_LOADDIAG                     14       /* BMP  */
#define RES_LOADING                      15       /* BMP  */
#define RES_MAINAREA                     16       /* BMP  */
#define RES_MOUSE                        17       /* BMP  */
#define RES_NUMBERS                      18       /* BMP  */
#define RES_NUMS_HI                      19       /* BMP  */
#define RES_OVERCURS                     20       /* BMP  */
#define RES_PAGEBUTN                     21       /* BMP  */
#define RES_PAL_COL                      22       /* BMP  */
#define RES_PALCURS                      23       /* BMP  */
#define RES_PROPFONT                     24       /* BMP  */
#define RES_SAVING                       25       /* BMP  */
#define RES_SM_PAL                       26       /* BMP  */
#define RES_TITLEBOX                     27       /* BMP  */
#define RES_VOL_BUTTONS                  28       /* BMP  */
#define RES_WRONG_D                      29       /* BMP  */
#define RES_WRONG_L                      30       /* BMP  */
#define RES_COUNT                        31

