/* Allegro datafile object indexes, produced by grabber v3.12 */
/* Datafile: c:\projects\dampbn\res\dampbn.dat */
/* Date: Thu May 26 15:20:27 2022 */
/* Do not hand edit! */

#define RES_ARE_YOU_SURE                 0        /* BMP  */
#define RES_BG_LOWER                     1        /* BMP  */
#define RES_BG_RIGHT                     2        /* BMP  */
#define RES_BUTTONS                      3        /* BMP  */
#define RES_DRAWCURS                     4        /* BMP  */
#define RES_FINISHED                     5        /* BMP  */
#define RES_HELP_EXIT                    6        /* BMP  */
#define RES_HELP_NEXT                    7        /* BMP  */
#define RES_HELP_PREVIOUS                8        /* BMP  */
#define RES_HOLYGOAT                     9        /* BMP  */
#define RES_LG_CROSS                     10       /* BMP  */
#define RES_LG_DIA                       11       /* BMP  */
#define RES_LG_PAL                       12       /* BMP  */
#define RES_LOADDIAG                     13       /* BMP  */
#define RES_LOADING                      14       /* BMP  */
#define RES_MAINAREA                     15       /* BMP  */
#define RES_MOUSE                        16       /* BMP  */
#define RES_NUMBERS                      17       /* BMP  */
#define RES_NUMS_HI                      18       /* BMP  */
#define RES_OVERCURS                     19       /* BMP  */
#define RES_PAGEBUTN                     20       /* BMP  */
#define RES_PAL_COL                      21       /* BMP  */
#define RES_PALCURS                      22       /* BMP  */
#define RES_PROPFONT                     23       /* BMP  */
#define RES_SAVING                       24       /* BMP  */
#define RES_SM_PAL                       25       /* BMP  */
#define RES_TITLEBOX                     26       /* BMP  */
#define RES_WRONG_D                      27       /* BMP  */
#define RES_WRONG_L                      28       /* BMP  */
#define RES_COUNT                        29

